apiVersion: v1
baseDomain: smcloud.local
compute:
  - hyperthreading: Disabled
    name: worker
    replicas: 0 # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
controlPlane:
  hyperthreading: Disabled
  name: master
  replicas: 3
metadata:
  name: okd45 # Cluster name
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/16
      hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'
sshKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNHwD1++o3om/CI+gezckHGZ2ct3H6Flm8DjV2h/v+wtAMoRI41Agui/vYzix8iWFEiWYPhUanwvlEKa7vr2K97wFfJIisUgp6QMePDNSrlNURVKE70yxFprqcH6MclqaI0oYp5z+vPFzCqXjxpXCN47BdCyMFZ4JkP9Ye6ZCq4rj1hSyN/AGHQ1coOKeXVay5Mx8AX4raAOZlK8I/ZOXsu3Tx1WqDVTsSWam3+ArYqNCASluodmN1o+fHkpneUkcGQsTZh/OK1MuyzFCny7j0WeXK/NWTgbcVCtbrpWpm4u48toKj6FXcBTdi7WN0q1YNe4vXICSGQXUMrjOHgesrl/eIqt5GABwcsWHtUhCRLQSKQ97ec6FX1snNl6eTvlDRtKz12lCE6eImpQBoX5fMIQPPSMIWho39fqhFfun7syFFP4jz7Lqj7L1vAohKYf69G2ytmmjK7tG4kqW48kz1kM0hrLdYbMEwLgm2YgnOuDZ4WKBY8SBYSUn1p88FeO8= root@sm-epyc-centos8.smcloud.local"
